// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBs7eNAgj3q_gbYE3RT3-CI2Ps19SUJx8g',
    appId: '1:556892509400:web:382a11317045c0d7e033ad',
    messagingSenderId: '556892509400',
    projectId: 'rutvik-todo',
    authDomain: 'rutvik-todo.firebaseapp.com',
    storageBucket: 'rutvik-todo.appspot.com',
    measurementId: 'G-Y2JMKKXNT9',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyClS1k85ukBNFMNqrZ6vefJzIB4zsnvVOk',
    appId: '1:556892509400:android:78ab9f89276a521ce033ad',
    messagingSenderId: '556892509400',
    projectId: 'rutvik-todo',
    storageBucket: 'rutvik-todo.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAJw2YC7TG6rtdm_SxuBLa7x--UUQZ5AqY',
    appId: '1:556892509400:ios:c733ed0bc719b0d4e033ad',
    messagingSenderId: '556892509400',
    projectId: 'rutvik-todo',
    storageBucket: 'rutvik-todo.appspot.com',
    iosBundleId: 'com.example.toDoList',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAJw2YC7TG6rtdm_SxuBLa7x--UUQZ5AqY',
    appId: '1:556892509400:ios:4a7d3006d9d541dce033ad',
    messagingSenderId: '556892509400',
    projectId: 'rutvik-todo',
    storageBucket: 'rutvik-todo.appspot.com',
    iosBundleId: 'com.example.toDoList.RunnerTests',
  );
}
